<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ps3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="piekarski_ps3_files/libs/clipboard/clipboard.min.js"></script>
<script src="piekarski_ps3_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="piekarski_ps3_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="piekarski_ps3_files/libs/quarto-html/popper.min.js"></script>
<script src="piekarski_ps3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="piekarski_ps3_files/libs/quarto-html/anchor.min.js"></script>
<link href="piekarski_ps3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="piekarski_ps3_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="piekarski_ps3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="piekarski_ps3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="piekarski_ps3_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ps3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="gov-51-ps-3" class="level1">
<h1>GOV 51 PS 3</h1>
<p>Author: Sage Piekarski</p>
<p>March 28th, 2025</p>
<section id="setup-and-data-exploration" class="level2">
<h2 class="anchored" data-anchor-id="setup-and-data-exploration">1 Setup and Data Exploration</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q1.1</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(tidyverse)) <span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tidyverse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   4.0.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(glmnet)) <span class="fu">install.packages</span>(<span class="st">"glmnet"</span>);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: glmnet
Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loaded glmnet 4.1-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(knitr)) <span class="fu">install.packages</span>(<span class="st">"knitr"</span>);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: knitr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>compas <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/raw/compas_clean.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#Q1.2 There are 7,214 observations and 17 variables in the dataset. The unit of observations are individuals accused of crimes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q1.3</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(compas<span class="sc">$</span>recidivism)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4506515</code></pre>
</div>
</div>
<p>#Q1.3 The overall recidivism rate in the data is 45.07%. The recidivism outcome is binary as recidivism is either 1 or 0 for whether someone was rearrested within two years or not. This is important when we interpret the predictions from the model, because the LPM creates a line of best fit and can predict values outside of 0 to 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q1.4</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>summ_stat_table <span class="ot">&lt;-</span> compas <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="at">mean =</span>  <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">sd =</span> <span class="sc">~</span><span class="fu">sd</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>summ_stat_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  recidivism_mean recidivism_sd age_mean   age_sd female_mean female_sd
1       0.4506515     0.4975933 34.81799 11.88892    0.193374  0.394971
  black_mean  black_sd hispanic_mean hispanic_sd  asian_mean   asian_sd
1  0.5123371 0.4998824    0.08830053   0.2837511 0.004435819 0.06645867
  other_race_mean other_race_sd native_american_mean native_american_sd
1       0.0522595     0.2225653          0.002495148         0.04989256
  priors_count_mean priors_count_sd felony_mean felony_sd juv_fel_count_mean
1          3.472415        4.882538   0.6467979  0.477998         0.06723039
  juv_fel_count_sd juv_misd_count_mean juv_misd_count_sd juv_other_count_mean
1        0.4739715          0.09093429         0.4852385            0.1093707
  juv_other_count_sd has_juv_felony_mean has_juv_felony_sd has_juv_misd_mean
1          0.5015858          0.03909066         0.1938241        0.05752703
  has_juv_misd_sd age_under_25_mean age_under_25_sd age_25_45_mean age_25_45_sd
1        0.232863          0.211949       0.4087172      0.5695869    0.4951683</code></pre>
</div>
</div>
<p>#Q1.4 Some of the variables with the most variation are age and priors_count. Some of the variables with the least variation are native_american and asian.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q1.5 Create a bar chart showing the recidivism rate by number of prior offenses (priors_count). Group priors_count into categories: 0, 1–2, 3–5, 6–10, and 11+. </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>compas <span class="ot">&lt;-</span> compas <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">priors_ct =</span> <span class="fu">case_when</span>(priors_count <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"0"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                                  priors_count <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span> <span class="sc">~</span> <span class="st">"1-2"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                                  priors_count <span class="sc">%in%</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">5</span> <span class="sc">~</span> <span class="st">"3-5"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                                  priors_count <span class="sc">%in%</span> <span class="dv">6</span><span class="sc">:</span><span class="dv">10</span> <span class="sc">~</span> <span class="st">"6-10"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                                  priors_count <span class="sc">&gt;=</span> <span class="dv">11</span> <span class="sc">~</span> <span class="st">"11+"</span>),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">priors_ct =</span> <span class="fu">factor</span>(priors_ct, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1-2"</span>, <span class="st">"3-5"</span>, <span class="st">"6-10"</span>, <span class="st">"11+"</span>)))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>recid_rt_priors <span class="ot">&lt;-</span> compas <span class="sc">%&gt;%</span> </span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(priors_ct) <span class="sc">%&gt;%</span> </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">recid_rate =</span> <span class="fu">mean</span>(recidivism, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(recid_rt_priors, <span class="fu">aes</span>(<span class="at">x =</span> priors_ct, <span class="at">y =</span> recid_rate)) <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"cornflowerblue"</span>) <span class="sc">+</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Recidivism Rate by Number of Prior Offenses"</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Number of Prior Offenses"</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Recidivism Rate"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="piekarski_ps3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>#Q1.5 Based on this bar chart, it appears as though a higher recidivism rate is associated with a larger number of prior offenses.</p>
</section>
<section id="ols-baseline" class="level2">
<h2 class="anchored" data-anchor-id="ols-baseline">2 OLS Baseline</h2>
<p>#Q2.1</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q2.1</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">51</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(compas)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>train_idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> <span class="fu">floor</span>(<span class="fl">0.8</span> <span class="sc">*</span> n))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> compas[train_idx, ]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> compas[<span class="sc">-</span>train_idx, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#Q2.1 The Test set has 1,443 observations and the Train set has 5,771 observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q2.2</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  recidivism <span class="sc">~</span> age <span class="sc">+</span> female <span class="sc">+</span> black <span class="sc">+</span> hispanic <span class="sc">+</span> asian <span class="sc">+</span> other_race <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    native_american <span class="sc">+</span> priors_count <span class="sc">+</span> felony <span class="sc">+</span> juv_fel_count <span class="sc">+</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    juv_misd_count <span class="sc">+</span> juv_other_count <span class="sc">+</span> has_juv_felony <span class="sc">+</span> has_juv_misd <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    age_under_25 <span class="sc">+</span> age_25_45,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the summary</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recidivism ~ age + female + black + hispanic + asian + 
    other_race + native_american + priors_count + felony + juv_fel_count + 
    juv_misd_count + juv_other_count + has_juv_felony + has_juv_misd + 
    age_under_25 + age_25_45, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.3347 -0.3966 -0.1892  0.4520  1.1865 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      0.732659   0.065429  11.198  &lt; 2e-16 ***
age             -0.010259   0.001169  -8.772  &lt; 2e-16 ***
female          -0.059808   0.015632  -3.826 0.000132 ***
black            0.012266   0.014002   0.876 0.381049    
hispanic        -0.031099   0.023196  -1.341 0.180073    
asian           -0.035871   0.092911  -0.386 0.699452    
other_race      -0.046504   0.028482  -1.633 0.102577    
native_american -0.020283   0.119810  -0.169 0.865572    
priors_count     0.029532   0.001401  21.072  &lt; 2e-16 ***
felony           0.037706   0.012938   2.914 0.003578 ** 
juv_fel_count    0.005821   0.017516   0.332 0.739647    
juv_misd_count  -0.028568   0.018950  -1.508 0.131723    
juv_other_count  0.023089   0.012614   1.830 0.067244 .  
has_juv_felony   0.041631   0.044485   0.936 0.349395    
has_juv_misd     0.081995   0.039875   2.056 0.039802 *  
age_under_25    -0.015671   0.040972  -0.382 0.702119    
age_25_45       -0.081454   0.028916  -2.817 0.004865 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4613 on 5754 degrees of freedom
Multiple R-squared:  0.1429,    Adjusted R-squared:  0.1405 
F-statistic: 59.95 on 16 and 5754 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>#Q2.2 At the 5% level, the predictors that are statistically significant are age, female, priors_count, felony, has_juv_misd, and age_25_45.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q2.3</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="cf">function</span>(actual, predicted) {<span class="fu">sqrt</span>(<span class="fu">mean</span>((predicted <span class="sc">-</span> actual)<span class="sc">^</span><span class="dv">2</span>))}</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>rmse_train_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, <span class="at">newdata =</span> train) </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>rmse_train <span class="ot">&lt;-</span> <span class="fu">rmse</span>(train<span class="sc">$</span>recidivism, rmse_train_pred)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>rmse_train</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4605811</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>rmse_test_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, <span class="at">newdata =</span> test) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>rmse_test <span class="ot">&lt;-</span> <span class="fu">rmse</span>(test<span class="sc">$</span>recidivism, rmse_test_pred)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>rmse_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.462227</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>rmse_test <span class="sc">-</span> rmse_train </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001645971</code></pre>
</div>
</div>
<p>#Q2.3 The in-sample RMSE (predictions on the training data) is 0.4605811. The out-of-sample RMSE (predictions on the test data) is 0.462227. The gap between in-sample and out-of-sample RMSE is 0.001645971. With 16 predictors, the OLS is likely not overfitting. I believe this because the gap between the two sets is very small indicating that the two RMSE’s are very similar to each other. Thus, it doesn’t appear as though the model is overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q2.4</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">51</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">length.out =</span> <span class="fu">nrow</span>(train)))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>rmse_cv <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">5</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) {</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>train_k <span class="ot">&lt;-</span> train[folds <span class="sc">!=</span> k, ]</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>test_k <span class="ot">&lt;-</span> train[folds <span class="sc">==</span> k, ]</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>model_k <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  recidivism <span class="sc">~</span> age <span class="sc">+</span> female <span class="sc">+</span> black <span class="sc">+</span> hispanic <span class="sc">+</span> asian <span class="sc">+</span> other_race <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    native_american <span class="sc">+</span> priors_count <span class="sc">+</span> felony <span class="sc">+</span> juv_fel_count <span class="sc">+</span> </span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    juv_misd_count <span class="sc">+</span> juv_other_count <span class="sc">+</span> has_juv_felony <span class="sc">+</span> has_juv_misd <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    age_under_25 <span class="sc">+</span> age_25_45,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_k)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>pred_k <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_k, <span class="at">newdata =</span> test_k)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>rmse_cv[k] <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_k<span class="sc">$</span>recidivism <span class="sc">-</span> pred_k)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(rmse_cv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4620144</code></pre>
</div>
</div>
<p>#Q2.4 (A) The 5-fold CV estimate of RMSE is 0.4620144. This appears to be the exact same as the out-of-sample RMSE (predictions on the test data) which was 0.462227. (B) In my own words, cross-validation is more reliable than a single train/test split because cross-validation is more immune to errors due to within group variation. As such, a single train/test split is reliant on which observations are in which group, but cross-validation uses multiple splits so it gives a more reliable output value. (C) Finally, when we use cv.glmnet() later, it does this same process internally to choose the penalty parameter 𝜆. Cross-validation is the right tool for choosing 𝜆, because it essentially creates room for the creation of “new data” many times so that it is not just on the training data. For that reason it is reliable for out of sample predictions and can determine a good penalty parameter.</p>
<p>3 The Kitchen Sink: What Happens When You Add Too Many Predictors?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q3.1</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#somehow my dataset got all mixed up so i am starting fresh</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>compas <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/raw/compas_clean.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 7214 Columns: 17
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (17): recidivism, age, female, black, hispanic, asian, other_race, nativ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">51</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(compas)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>train_idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> <span class="fu">floor</span>(<span class="fl">0.8</span> <span class="sc">*</span> n))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> compas[train_idx, ]</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> compas[<span class="sc">-</span>train_idx, ]</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># recreate full interaction matrices</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>f_full <span class="ot">&lt;-</span> recidivism <span class="sc">~</span> (.)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">I</span>(age<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(priors_count<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">I</span>(juv_fel_count<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(juv_misd_count<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">I</span>(juv_other_count<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>X_train <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(f_full, <span class="at">data =</span> train)[, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(X_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 141</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Full interaction formula</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>f_full <span class="ot">&lt;-</span> recidivism <span class="sc">~</span> (.)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">I</span>(age<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(priors_count<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">I</span>(juv_fel_count<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(juv_misd_count<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">I</span>(juv_other_count<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create design matrices for glmnet (we'll need these later)</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>X_train <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(f_full, <span class="at">data =</span> train)[, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>X_test <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(f_full, <span class="at">data =</span> test)[, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> train<span class="sc">$</span>recidivism</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>y_test <span class="ot">&lt;-</span> test<span class="sc">$</span>recidivism</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># How many features now?</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(X_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 141</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="dv">5771</span><span class="sc">/</span><span class="dv">141</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40.92908</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "recidivism"      "age"             "female"          "black"          
 [5] "hispanic"        "asian"           "other_race"      "native_american"
 [9] "priors_count"    "felony"          "juv_fel_count"   "juv_misd_count" 
[13] "juv_other_count" "has_juv_felony"  "has_juv_misd"    "age_under_25"   
[17] "age_25_45"      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(compas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "recidivism"      "age"             "female"          "black"          
 [5] "hispanic"        "asian"           "other_race"      "native_american"
 [9] "priors_count"    "felony"          "juv_fel_count"   "juv_misd_count" 
[13] "juv_other_count" "has_juv_felony"  "has_juv_misd"    "age_under_25"   
[17] "age_25_45"      </code></pre>
</div>
</div>
<p>#Q1.3 The expanded model has 141 features. The ratio of training observations to predictors is 40.93.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q1.3</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co">#fit the model</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>ols_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(f_full, <span class="at">data =</span> train)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ols_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = f_full, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.0953 -0.3594 -0.1684  0.4227  0.9457 

Coefficients: (19 not defined because of singularities)
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      1.1551097  0.5148950   2.243 0.024910 *  
age                             -0.0305786  0.0175651  -1.741 0.081761 .  
female                          -0.2444590  0.1686000  -1.450 0.147132    
black                            0.2376319  0.1467693   1.619 0.105485    
hispanic                        -0.3240049  0.2285331  -1.418 0.156316    
asian                            0.2965316  0.8448337   0.351 0.725606    
other_race                       0.2813242  0.3104545   0.906 0.364885    
native_american                 -2.0400162  1.5889444  -1.284 0.199236    
priors_count                     0.0913210  0.0151112   6.043 1.61e-09 ***
felony                          -0.0514326  0.1342293  -0.383 0.701608    
juv_fel_count                   -0.5575596  0.4239097  -1.315 0.188469    
juv_misd_count                   0.1089302  0.4120444   0.264 0.791508    
juv_other_count                 -0.4259516  0.2510160  -1.697 0.089769 .  
has_juv_felony                   1.3521237  0.7956703   1.699 0.089308 .  
has_juv_misd                     0.1935748  0.4067433   0.476 0.634154    
age_under_25                     1.1062102  0.4892344   2.261 0.023791 *  
age_25_45                       -0.3668794  0.3435381  -1.068 0.285592    
I(age^2)                         0.0002278  0.0001499   1.519 0.128820    
I(priors_count^2)               -0.0010879  0.0001661  -6.551 6.24e-11 ***
I(juv_fel_count^2)               0.0070753  0.0113780   0.622 0.534070    
I(juv_misd_count^2)             -0.0034125  0.0080573  -0.424 0.671927    
I(juv_other_count^2)            -0.0130587  0.0039558  -3.301 0.000969 ***
age:female                       0.0029906  0.0030796   0.971 0.331537    
age:black                       -0.0039776  0.0026660  -1.492 0.135761    
age:hispanic                     0.0055519  0.0040958   1.356 0.175312    
age:asian                       -0.0084736  0.0164064  -0.516 0.605537    
age:other_race                  -0.0055319  0.0057565  -0.961 0.336598    
age:native_american              0.0236109  0.0342640   0.689 0.490796    
age:priors_count                -0.0007114  0.0002756  -2.581 0.009863 ** 
age:felony                       0.0006841  0.0024215   0.283 0.777550    
age:juv_fel_count                0.0109428  0.0085913   1.274 0.202817    
age:juv_misd_count              -0.0001320  0.0059211  -0.022 0.982213    
age:juv_other_count              0.0096670  0.0051757   1.868 0.061845 .  
age:has_juv_felony              -0.0295047  0.0161621  -1.826 0.067971 .  
age:has_juv_misd                 0.0056808  0.0121579   0.467 0.640334    
age:age_under_25                -0.0572618  0.0147898  -3.872 0.000109 ***
age:age_25_45                    0.0069654  0.0074505   0.935 0.349886    
female:black                    -0.0517525  0.0346223  -1.495 0.135029    
female:hispanic                  0.0326060  0.0625475   0.521 0.602178    
female:asian                    -0.0809454  0.3545478  -0.228 0.819417    
female:other_race                0.0229529  0.0729514   0.315 0.753052    
female:native_american           0.6905694  0.4378663   1.577 0.114823    
female:priors_count              0.0025635  0.0043761   0.586 0.558047    
female:felony                    0.0596173  0.0325969   1.829 0.067464 .  
female:juv_fel_count             0.2800096  0.2407757   1.163 0.244900    
female:juv_misd_count            0.0871017  0.1217448   0.715 0.474364    
female:juv_other_count          -0.0301570  0.0515244  -0.585 0.558372    
female:has_juv_felony           -0.3273675  0.3383898  -0.967 0.333372    
female:has_juv_misd             -0.2129212  0.1814631  -1.173 0.240702    
female:age_under_25              0.0272527  0.1049790   0.260 0.795180    
female:age_25_45                 0.1230583  0.0728014   1.690 0.091020 .  
black:hispanic                          NA         NA      NA       NA    
black:asian                             NA         NA      NA       NA    
black:other_race                        NA         NA      NA       NA    
black:native_american                   NA         NA      NA       NA    
black:priors_count              -0.0022046  0.0034835  -0.633 0.526836    
black:felony                    -0.0046156  0.0293382  -0.157 0.874995    
black:juv_fel_count              0.0356147  0.0707868   0.503 0.614895    
black:juv_misd_count             0.0480814  0.0944720   0.509 0.610808    
black:juv_other_count            0.0872965  0.0336582   2.594 0.009522 ** 
black:has_juv_felony            -0.0513688  0.1553154  -0.331 0.740854    
black:has_juv_misd              -0.2602546  0.1463050  -1.779 0.075318 .  
black:age_under_25              -0.0356877  0.0935869  -0.381 0.702971    
black:age_25_45                 -0.1137494  0.0653889  -1.740 0.081987 .  
hispanic:asian                          NA         NA      NA       NA    
hispanic:other_race                     NA         NA      NA       NA    
hispanic:native_american                NA         NA      NA       NA    
hispanic:priors_count           -0.0078001  0.0069857  -1.117 0.264221    
hispanic:felony                 -0.0005248  0.0482532  -0.011 0.991322    
hispanic:juv_fel_count           0.0083463  0.3626326   0.023 0.981638    
hispanic:juv_misd_count          0.2583995  0.1672675   1.545 0.122444    
hispanic:juv_other_count        -0.0154792  0.0671421  -0.231 0.817678    
hispanic:has_juv_felony          0.1713739  0.4508125   0.380 0.703852    
hispanic:has_juv_misd           -0.6392279  0.2840561  -2.250 0.024465 *  
hispanic:age_under_25            0.2433515  0.1474856   1.650 0.098998 .  
hispanic:age_25_45               0.1217762  0.1008102   1.208 0.227108    
asian:other_race                        NA         NA      NA       NA    
asian:native_american                   NA         NA      NA       NA    
asian:priors_count              -0.0038205  0.0432000  -0.088 0.929531    
asian:felony                     0.4670628  0.2218479   2.105 0.035307 *  
asian:juv_fel_count                     NA         NA      NA       NA    
asian:juv_misd_count             0.0398813  0.5321017   0.075 0.940257    
asian:juv_other_count            0.3734155  0.5320088   0.702 0.482772    
asian:has_juv_felony                    NA         NA      NA       NA    
asian:has_juv_misd                      NA         NA      NA       NA    
asian:age_under_25              -0.4821097  0.5286063  -0.912 0.361787    
asian:age_25_45                 -0.5355302  0.3599055  -1.488 0.136813    
other_race:native_american              NA         NA      NA       NA    
other_race:priors_count          0.0182971  0.0088049   2.078 0.037749 *  
other_race:felony                0.0051170  0.0588878   0.087 0.930759    
other_race:juv_fel_count         0.1150403  0.1994402   0.577 0.564087    
other_race:juv_misd_count        0.6818468  0.3724722   1.831 0.067213 .  
other_race:juv_other_count      -0.1918835  0.2008675  -0.955 0.339480    
other_race:has_juv_felony       -0.8132442  0.4989548  -1.630 0.103179    
other_race:has_juv_misd         -1.1514671  0.5622809  -2.048 0.040621 *  
other_race:age_under_25         -0.2282138  0.1951683  -1.169 0.242325    
other_race:age_25_45            -0.1812063  0.1325535  -1.367 0.171666    
native_american:priors_count     0.0346085  0.0430848   0.803 0.421856    
native_american:felony           0.0271712  0.4638793   0.059 0.953294    
native_american:juv_fel_count    0.1667790  0.3950912   0.422 0.672948    
native_american:juv_misd_count   1.7277249  1.0476839   1.649 0.099185 .  
native_american:juv_other_count -0.4085247  1.1949161  -0.342 0.732450    
native_american:has_juv_felony   0.1377065  0.8909649   0.155 0.877175    
native_american:has_juv_misd            NA         NA      NA       NA    
native_american:age_under_25            NA         NA      NA       NA    
native_american:age_25_45        0.8120286  0.6222716   1.305 0.191966    
priors_count:felony             -0.0033910  0.0033602  -1.009 0.312927    
priors_count:juv_fel_count      -0.0082082  0.0106010  -0.774 0.438797    
priors_count:juv_misd_count      0.0013674  0.0043074   0.317 0.750913    
priors_count:juv_other_count    -0.0019909  0.0042061  -0.473 0.636000    
priors_count:has_juv_felony      0.0078730  0.0167883   0.469 0.639119    
priors_count:has_juv_misd       -0.0034381  0.0098590  -0.349 0.727309    
priors_count:age_under_25        0.0090858  0.0115427   0.787 0.431227    
priors_count:age_25_45          -0.0104959  0.0061901  -1.696 0.090018 .  
felony:juv_fel_count             0.0679306  0.0854094   0.795 0.426441    
felony:juv_misd_count            0.0422370  0.0653317   0.647 0.517981    
felony:juv_other_count           0.0284397  0.0333258   0.853 0.393484    
felony:has_juv_felony           -0.1654420  0.1574766  -1.051 0.293496    
felony:has_juv_misd             -0.0278098  0.1120348  -0.248 0.803969    
felony:age_under_25              0.0078655  0.0852588   0.092 0.926499    
felony:age_25_45                 0.0701870  0.0600663   1.168 0.242658    
juv_fel_count:juv_misd_count    -0.0284732  0.0903062  -0.315 0.752549    
juv_fel_count:juv_other_count    0.0974531  0.0777039   1.254 0.209836    
juv_fel_count:has_juv_felony            NA         NA      NA       NA    
juv_fel_count:has_juv_misd       0.0410029  0.1443531   0.284 0.776385    
juv_fel_count:age_under_25       0.2676663  0.2975257   0.900 0.368350    
juv_fel_count:age_25_45          0.1445626  0.2282362   0.633 0.526504    
juv_misd_count:juv_other_count   0.0269002  0.0190796   1.410 0.158626    
juv_misd_count:has_juv_felony   -0.0249327  0.1203668  -0.207 0.835909    
juv_misd_count:has_juv_misd             NA         NA      NA       NA    
juv_misd_count:age_under_25     -0.2274696  0.3680658  -0.618 0.536591    
juv_misd_count:age_25_45        -0.2204621  0.3619583  -0.609 0.542495    
juv_other_count:has_juv_felony  -0.1707255  0.1068541  -1.598 0.110156    
juv_other_count:has_juv_misd    -0.0437879  0.0501791  -0.873 0.382900    
juv_other_count:age_under_25     0.2426995  0.1669067   1.454 0.145973    
juv_other_count:age_25_45        0.1107962  0.1377530   0.804 0.421252    
has_juv_felony:has_juv_misd     -0.0960487  0.2426893  -0.396 0.692291    
has_juv_felony:age_under_25     -0.5717520  0.4985315  -1.147 0.251483    
has_juv_felony:age_25_45        -0.1828306  0.3647896  -0.501 0.616254    
has_juv_misd:age_under_25       -0.0640918  0.1424141  -0.450 0.652700    
has_juv_misd:age_25_45                  NA         NA      NA       NA    
age_under_25:age_25_45                  NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4534 on 5648 degrees of freedom
Multiple R-squared:  0.1871,    Adjusted R-squared:  0.1695 
F-statistic: 10.66 on 122 and 5648 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute rmses</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>rmse_train_pred2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(ols_full, <span class="at">newdata =</span> train) </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>rmse_train2 <span class="ot">&lt;-</span> <span class="fu">rmse</span>(train<span class="sc">$</span>recidivism, rmse_train_pred2)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>rmse_train2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4485474</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>rmse_test_pred2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(ols_full, <span class="at">newdata =</span> test) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(ols_full, newdata = test): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>rmse_test2 <span class="ot">&lt;-</span> <span class="fu">rmse</span>(test<span class="sc">$</span>recidivism, rmse_test_pred2)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>rmse_test2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4890411</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>rmse_test2 <span class="sc">-</span> rmse_train2 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04049367</code></pre>
</div>
</div>
<p>#Q3.2 (A) The in-sample RMSE for this model is 0.4485. (B) The out-of-sample RMSE is 0.4890. (C) The in-sample/out-of-sample gap is 0.0405. Compare to the simple 19-predictor OLS, this gap is quite a bit larger than the original gap of 0.0016. This indicates that likely the new OLS model is overfitting because the gap is so much larger. We get a larger gap when the model overfits because when more predictors are added they bring in more noise to the equation.</p>
<p>#Q3.3 Adding 180 interaction terms made the model’s in-sample fit better but its out-of-sample predictions worse because adding all of these new terms allows the model to fit the training data better. However, when you try to apply this to new data sets like in the test set, there are so many new predictors with more noise which makes the predictions on new data worse. This is called overfitting!</p>
</section>
<section id="ridge-regression-shrink-everything" class="level2">
<h2 class="anchored" data-anchor-id="ridge-regression-shrink-everything">4 Ridge Regression: Shrink Everything</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q4.1</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">51</span>) <span class="co"># for reproducible CV folds</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>cv_ridge <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X_train, y_train, <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">nfolds =</span> <span class="dv">10</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>cv_ridge<span class="sc">$</span>lambda.min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01376272</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv_ridge)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="piekarski_ps3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>#Q4.1 (A)The optimal 𝜆 selected by cross-validation is 0.0138. (B) This plot shows the projected fit of a given model to a new data set that the model was not trained on. In our case, it shows the expected fit of the model on the test set after being trained on the train set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q4.2</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co">#compute rmses</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>rmse_ridge_cv_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(cv_ridge, <span class="at">newx =</span> X_test, <span class="at">s =</span> <span class="st">"lambda.min"</span>) </span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>rmse_ridge <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((y_test <span class="sc">-</span> rmse_ridge_cv_pred)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>rmse_ridge</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4700385</code></pre>
</div>
</div>
<p>#Q4.2 The out-of-sample RMSE for Ridge is 0.47. The simple OLS (16 vars) has an out-of-sample RMSE of 0.4622 and the kitchen-sink OLS (~141 vars) had one of 0.489. The new ridge regression RMSE seems to be just in between the RMSE from the OLS simple regression and the kitchen-sink OLS. This means the ridge reduces overfitting by shrinking the coefficients. In doing so, they trade some bias for less variance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q4.3</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(cv_ridge, <span class="at">s =</span> <span class="st">"lambda.min"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>142 x 1 sparse Matrix of class "dgCMatrix"
                                   lambda.min
(Intercept)                      6.240172e-01
age                             -7.146883e-03
female                          -6.310304e-02
black                            8.833220e-02
hispanic                        -9.399273e-02
asian                           -9.631129e-02
other_race                       1.172025e-02
native_american                 -3.951980e-01
priors_count                     2.814853e-02
felony                           3.058693e-02
juv_fel_count                    1.076914e-02
juv_misd_count                   4.656344e-03
juv_other_count                 -1.444343e-03
has_juv_felony                   1.081862e-01
has_juv_misd                     9.650399e-02
age_under_25                     8.001654e-02
age_25_45                       -1.704785e-02
I(age^2)                        -8.791274e-06
I(priors_count^2)               -7.997212e-04
I(juv_fel_count^2)               1.229990e-03
I(juv_misd_count^2)             -5.644604e-04
I(juv_other_count^2)            -9.162454e-03
age:female                      -5.157715e-04
age:black                       -1.586003e-03
age:hispanic                     1.410240e-03
age:asian                       -6.709189e-04
age:other_race                  -9.495021e-04
age:native_american             -4.925668e-03
age:priors_count                 2.275284e-04
age:felony                      -9.447363e-04
age:juv_fel_count               -6.818760e-04
age:juv_misd_count              -8.816889e-04
age:juv_other_count              5.954111e-04
age:has_juv_felony              -3.010842e-03
age:has_juv_misd                 1.839858e-03
age:age_under_25                -5.473185e-03
age:age_25_45                   -2.113682e-03
female:black                    -5.557765e-02
female:hispanic                  1.584091e-02
female:asian                    -5.213759e-02
female:other_race                1.963641e-02
female:native_american           5.948221e-01
female:priors_count              5.893477e-03
female:felony                    5.244157e-02
female:juv_fel_count             1.769619e-01
female:juv_misd_count            4.550161e-02
female:juv_other_count          -3.235086e-02
female:has_juv_felony           -2.090400e-01
female:has_juv_misd             -1.424213e-01
female:age_under_25             -7.660951e-02
female:age_25_45                 4.893753e-02
black:hispanic                   .           
black:asian                      .           
black:other_race                 .           
black:native_american            .           
black:priors_count               2.533953e-04
black:felony                    -2.439377e-03
black:juv_fel_count              5.469707e-03
black:juv_misd_count            -1.509481e-02
black:juv_other_count            7.799527e-02
black:has_juv_felony             2.720883e-02
black:has_juv_misd              -1.319078e-01
black:age_under_25               5.796655e-02
black:age_25_45                 -4.565325e-02
hispanic:asian                   .           
hispanic:other_race              .           
hispanic:native_american         .           
hispanic:priors_count           -4.246163e-03
hispanic:felony                 -4.338215e-03
hispanic:juv_fel_count           7.029226e-02
hispanic:juv_misd_count          1.920545e-01
hispanic:juv_other_count        -2.622615e-02
hispanic:has_juv_felony          1.554805e-01
hispanic:has_juv_misd           -5.198679e-01
hispanic:age_under_25            1.107656e-01
hispanic:age_25_45               1.912834e-02
asian:other_race                 .           
asian:native_american            .           
asian:priors_count               1.070921e-02
asian:felony                     3.956993e-01
asian:juv_fel_count              .           
asian:juv_misd_count             1.513275e-01
asian:juv_other_count            5.299783e-01
asian:has_juv_felony             .           
asian:has_juv_misd               1.545502e-01
asian:age_under_25              -3.048093e-01
asian:age_25_45                 -3.728278e-01
other_race:native_american       .           
other_race:priors_count          1.647782e-02
other_race:felony                1.394422e-02
other_race:juv_fel_count        -3.977307e-03
other_race:juv_misd_count        4.080779e-01
other_race:juv_other_count      -1.644768e-01
other_race:has_juv_felony       -5.716222e-01
other_race:has_juv_misd         -6.862896e-01
other_race:age_under_25         -3.777723e-02
other_race:age_25_45            -7.315482e-02
native_american:priors_count     2.116843e-02
native_american:felony          -2.371184e-02
native_american:juv_fel_count    5.667275e-02
native_american:juv_misd_count   2.968025e-01
native_american:juv_other_count -3.425949e-02
native_american:has_juv_felony   4.365763e-01
native_american:has_juv_misd     2.862483e-01
native_american:age_under_25     2.747477e-01
native_american:age_25_45        1.892453e-01
priors_count:felony              1.193952e-04
priors_count:juv_fel_count      -1.179082e-03
priors_count:juv_misd_count     -3.065749e-04
priors_count:juv_other_count     1.076960e-03
priors_count:has_juv_felony     -5.526281e-03
priors_count:has_juv_misd        1.947317e-04
priors_count:age_under_25        2.603582e-02
priors_count:age_25_45           9.792224e-03
felony:juv_fel_count             2.748596e-02
felony:juv_misd_count            1.852399e-02
felony:juv_other_count           1.716179e-02
felony:has_juv_felony           -4.472484e-02
felony:has_juv_misd             -4.121938e-03
felony:age_under_25             -9.289630e-03
felony:age_25_45                 3.091927e-02
juv_fel_count:juv_misd_count    -2.957597e-02
juv_fel_count:juv_other_count    3.162266e-02
juv_fel_count:has_juv_felony     1.345364e-02
juv_fel_count:has_juv_misd      -2.788563e-03
juv_fel_count:age_under_25       3.142700e-02
juv_fel_count:age_25_45         -1.221178e-02
juv_misd_count:juv_other_count   1.706586e-02
juv_misd_count:has_juv_felony   -2.571617e-02
juv_misd_count:has_juv_misd      6.921910e-03
juv_misd_count:age_under_25     -1.273201e-02
juv_misd_count:age_25_45        -8.842862e-03
juv_other_count:has_juv_felony  -6.655421e-02
juv_other_count:has_juv_misd    -3.578465e-02
juv_other_count:age_under_25     1.919057e-02
juv_other_count:age_25_45       -4.688677e-02
has_juv_felony:has_juv_misd     -1.885695e-03
has_juv_felony:age_under_25     -2.218784e-02
has_juv_felony:age_25_45         8.704239e-02
has_juv_misd:age_under_25       -6.167165e-03
has_juv_misd:age_25_45           5.805613e-02
age_under_25:age_25_45           .           </code></pre>
</div>
</div>
<p>#Q4.3 It doesn’t seem as though ridge eliminated any variables. The ridge is just shrinking the coefficients it is not bringing any of them directly to zero so that they are removed.</p>
</section>
<section id="lasso-regression-shrink-and-select" class="level2">
<h2 class="anchored" data-anchor-id="lasso-regression-shrink-and-select">5 LASSO Regression: Shrink and Select</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q5.1</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">51</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>cv_lasso <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X_train, y_train, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">nfolds =</span> <span class="dv">10</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>cv_lasso<span class="sc">$</span>lambda.min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.007694477</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv_lasso)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="piekarski_ps3_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>#Q5.1 The optimal 𝜆 is 0.007694.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q5.2</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>lasso_coefficients <span class="ot">&lt;-</span> <span class="fu">coef</span>(cv_lasso, <span class="at">s =</span> <span class="st">"lambda.min"</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>lasso_coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>142 x 1 sparse Matrix of class "dgCMatrix"
                                   lambda.min
(Intercept)                      5.968656e-01
age                             -7.723219e-03
female                          -5.767754e-03
black                            .           
hispanic                         .           
asian                            .           
other_race                       .           
native_american                  .           
priors_count                     3.556519e-02
felony                           2.138462e-02
juv_fel_count                    .           
juv_misd_count                   .           
juv_other_count                  .           
has_juv_felony                   .           
has_juv_misd                     .           
age_under_25                     .           
age_25_45                        .           
I(age^2)                         .           
I(priors_count^2)               -4.337116e-04
I(juv_fel_count^2)               .           
I(juv_misd_count^2)              .           
I(juv_other_count^2)            -2.220303e-03
age:female                      -1.274802e-04
age:black                        .           
age:hispanic                     .           
age:asian                        .           
age:other_race                   .           
age:native_american              .           
age:priors_count                 .           
age:felony                       .           
age:juv_fel_count                .           
age:juv_misd_count               .           
age:juv_other_count              .           
age:has_juv_felony               .           
age:has_juv_misd                 .           
age:age_under_25                 .           
age:age_25_45                   -8.609394e-04
female:black                    -1.955202e-02
female:hispanic                  .           
female:asian                     .           
female:other_race                .           
female:native_american           .           
female:priors_count              1.288987e-05
female:felony                    .           
female:juv_fel_count             .           
female:juv_misd_count            .           
female:juv_other_count           .           
female:has_juv_felony            .           
female:has_juv_misd              .           
female:age_under_25             -9.284022e-02
female:age_25_45                 .           
black:hispanic                   .           
black:asian                      .           
black:other_race                 .           
black:native_american            .           
black:priors_count               .           
black:felony                     .           
black:juv_fel_count              1.150518e-03
black:juv_misd_count             .           
black:juv_other_count            3.342919e-02
black:has_juv_felony             .           
black:has_juv_misd               .           
black:age_under_25               7.940064e-02
black:age_25_45                  .           
hispanic:asian                   .           
hispanic:other_race              .           
hispanic:native_american         .           
hispanic:priors_count            .           
hispanic:felony                  .           
hispanic:juv_fel_count           9.218711e-02
hispanic:juv_misd_count          .           
hispanic:juv_other_count         .           
hispanic:has_juv_felony          .           
hispanic:has_juv_misd            .           
hispanic:age_under_25            .           
hispanic:age_25_45              -8.940017e-03
asian:other_race                 .           
asian:native_american            .           
asian:priors_count               .           
asian:felony                     .           
asian:juv_fel_count              .           
asian:juv_misd_count             .           
asian:juv_other_count            .           
asian:has_juv_felony             .           
asian:has_juv_misd               .           
asian:age_under_25               .           
asian:age_25_45                 -2.166967e-02
other_race:native_american       .           
other_race:priors_count          1.547459e-04
other_race:felony                .           
other_race:juv_fel_count         .           
other_race:juv_misd_count        .           
other_race:juv_other_count       .           
other_race:has_juv_felony       -3.579049e-02
other_race:has_juv_misd          .           
other_race:age_under_25          .           
other_race:age_25_45            -1.748625e-02
native_american:priors_count     .           
native_american:felony           .           
native_american:juv_fel_count    .           
native_american:juv_misd_count   .           
native_american:juv_other_count  .           
native_american:has_juv_felony   .           
native_american:has_juv_misd     .           
native_american:age_under_25     .           
native_american:age_25_45        .           
priors_count:felony              .           
priors_count:juv_fel_count       .           
priors_count:juv_misd_count      .           
priors_count:juv_other_count     .           
priors_count:has_juv_felony      .           
priors_count:has_juv_misd        .           
priors_count:age_under_25        1.682224e-02
priors_count:age_25_45           2.040836e-03
felony:juv_fel_count             .           
felony:juv_misd_count            .           
felony:juv_other_count           .           
felony:has_juv_felony            .           
felony:has_juv_misd              4.124298e-03
felony:age_under_25              .           
felony:age_25_45                 .           
juv_fel_count:juv_misd_count     .           
juv_fel_count:juv_other_count    .           
juv_fel_count:has_juv_felony     .           
juv_fel_count:has_juv_misd       .           
juv_fel_count:age_under_25       7.147058e-03
juv_fel_count:age_25_45          .           
juv_misd_count:juv_other_count   .           
juv_misd_count:has_juv_felony   -2.591047e-03
juv_misd_count:has_juv_misd      .           
juv_misd_count:age_under_25      .           
juv_misd_count:age_25_45         .           
juv_other_count:has_juv_felony   .           
juv_other_count:has_juv_misd     .           
juv_other_count:age_under_25     1.918434e-02
juv_other_count:age_25_45        .           
has_juv_felony:has_juv_misd      .           
has_juv_felony:age_under_25      8.816157e-03
has_juv_felony:age_25_45         .           
has_juv_misd:age_under_25        .           
has_juv_misd:age_25_45           .           
age_under_25:age_25_45           .           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>nonzero_lasso_coeffs <span class="ot">&lt;-</span> <span class="fu">sum</span>(lasso_coefficients <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>nonzero_lasso_coeffs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>all <span class="ot">&lt;-</span> <span class="fu">length</span>(lasso_coefficients) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>all</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 141</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>survived <span class="ot">&lt;-</span> <span class="fu">sum</span>(lasso_coefficients[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>survived</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>eliminated <span class="ot">&lt;-</span> all <span class="sc">-</span> survived</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>eliminated</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 114</code></pre>
</div>
</div>
<p>#Q5.2</p>
<p>(a) Of the ~141 variables 27 survived (non-zero coeﬀicient) while 114 were eliminated.</p>
<p>(b)a few of the surviving interaction terms are age:female, black:juv_other_count, and felony:priors_ct6-10. These all seem to make substantive sense because age:female would indicate how the impact of age on recidivism would change across genders. Similarly black: juv_other_count would show the effect of juvenile offense counts across races and felony:prios_ct6-10 illustrates the impact of having 6 to 10 priors with whether the current charge is a felony.</p>
<p>(c) Baker (2025) argues that LASSO reduces “subjective discretion” in model building. What we see here illustrates this argument because it shows how LASSO automatically selects which variables to keep based on statistical evidence rather than other methodologies that allow the researcher to identify what to keep. This reduces subjective discretion because the choice is done automated by R rather than varying from person to person.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q5.3</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Q4.2</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="co">#compute rmses</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>rmse_lasso_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(cv_lasso, <span class="at">newx =</span> X_test, <span class="at">s =</span> <span class="st">"lambda.min"</span>) </span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>rmse_lasso <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((y_test <span class="sc">-</span> rmse_lasso_pred)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>rmse_lasso</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4592597</code></pre>
</div>
</div>
<p>#Q5.3 The out-of-sample RMSE for LASSO is 0.4593. The out-of-sample RMSE for Ridge was 0.47. The simple OLS (16 vars) has an out-of-sample RMSE of 0.4622 and the kitchen-sink OLS (~141 vars) had one of 0.489. The new lasso regression RMSE is the smallest of all of these regressions though it is quite close in value to the simple OLS model and the ridge.This means the lasso reduces overfitting by shrinking the coefficients and keeping the most important variables and predictors.</p>
</section>
<section id="model-comparison-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison-and-interpretation">6 Model Comparison and Interpretation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q6.1</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">51</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>cv_enet <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X_train, y_train, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">nfolds =</span> <span class="dv">10</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>lambda_enet <span class="ot">&lt;-</span> cv_enet<span class="sc">$</span>lambda.min</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>lambda_enet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.008806125</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute rmses</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>rmse_cv_enet_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(cv_enet, <span class="at">newx =</span> X_test, <span class="at">s =</span> <span class="st">"lambda.min"</span>) </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>rmse_cv_enet <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((y_test <span class="sc">-</span> rmse_cv_enet_pred)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>rmse_cv_enet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4583446</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#count variables</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>cv_enet_coefficients <span class="ot">&lt;-</span> <span class="fu">coef</span>(cv_enet, <span class="at">s =</span> <span class="st">"lambda.min"</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>survived_cv_enet <span class="ot">&lt;-</span> <span class="fu">sum</span>(cv_enet_coefficients[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>survived_cv_enet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 43</code></pre>
</div>
</div>
<p>#Q6.1 The out of sample RMSE is 0.4583 and it retains 43 variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q6.2</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>comparison <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"OLS (main effects, 16 vars)"</span>,</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"OLS (kitchen sink, 141 vars)"</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Ridge"</span>,</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"LASSO"</span>,</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Elastic Net"</span>),</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Predictors =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">141</span>, <span class="dv">141</span>, <span class="dv">27</span>, <span class="dv">43</span>),</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>                         <span class="st">'Out-of-Sample RMSE'</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">0.4622</span>, <span class="fl">0.4890</span>, <span class="fl">0.4700</span>, <span class="fl">0.4593</span>, <span class="fl">0.4583</span>))</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(comparison, <span class="at">digits =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Predictors</th>
<th style="text-align: right;">Out.of.Sample.RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">OLS (main effects, 16 vars)</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.4622</td>
</tr>
<tr class="even">
<td style="text-align: left;">OLS (kitchen sink, 141 vars)</td>
<td style="text-align: right;">141</td>
<td style="text-align: right;">0.4890</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ridge</td>
<td style="text-align: right;">141</td>
<td style="text-align: right;">0.4700</td>
</tr>
<tr class="even">
<td style="text-align: left;">LASSO</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">0.4593</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elastic Net</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.4583</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>#Q6.2 (a) The model with the lowest out-of-sample RMSE is the elastic net.</p>
<p>(b) The model with the best in-sample fit is likely the kitchen sink ols which is not the same model.</p>
<p>(c) Ultimately, this table teaches us much about the bias-variance tradeoff. As such, when more predictors are added to the point that there are perhaps too many predictors then it hurts test performance. Methods like Ridge, LASSO, and elastic net handle this by trading some bias for less variance, indicating a better out of sample fit and RMSE.</p>
<p>#Q6.3 Baker article connection</p>
<p>I found the Baker article really interesting. In Baker (2025) there are two experts in the Halliburton securities case who selected different peer firms and reached different conclusions about whether a stock drop was statistically significant. LASSO was able to help narrow the disagreement between dueling experts because it was able to take some subjectivity out of the equation. In this way, while before each indivdual expert would have chosen the variables or predictors they thought most important, the LASSO actually is able to automatically select predictors of most importance and shrink the coefficients of the predictors that are not very relevant to zero. As a result, the disagreement between the experts could likely be solved. Based on my experience with LASSO in this problem set, the aspect of the traditional OLS approach that gives the analyst the most room for manipulation would be which predictors to include. There are so many predictors that deciding which ones are the most important and how many to include is a bit of a tough decision. The researcher is really at the healm of making this decision and therefore I think it is probably the area with the most room for manipulation.</p>
<p>#Q6.4 Okay now suppose instead you wanted to know whether priors_count causes higher recidivism.</p>
<p>(a) The LASSO coeﬀicient on priors_count would not answer this causal question. This is because there are a number of Omitted variables and confounding variables that could be present. I actually just did a study in my econometrics class on this very same data where we studied the causal relationship using an instrumental variable.</p>
<p>(b) The difference between using regression for prediction versus using it for causal inference is first off the goal of what you are trying to see. Prediction allows you to predict the probability or occurence of something whereas causal inference is more about how one thing will directly cause another thing. As such, using lasso, prediction allows you to forecast or foresee but it doesn’t necessarily indicate a causal relationship as we just expressed due to the potentiality for biased outcomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Q6.5 </span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, <span class="at">newdata =</span> test)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>white <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(test<span class="sc">$</span>black <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> test<span class="sc">$</span>hispanic <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> test<span class="sc">$</span>asian <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>other_race <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> test<span class="sc">$</span>native_american <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>num_black <span class="ot">&lt;-</span> <span class="fu">sum</span>(test<span class="sc">$</span>black <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>num_white <span class="ot">&lt;-</span> <span class="fu">sum</span>(test<span class="sc">$</span>white <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>mean_pred_black <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>predicted[test<span class="sc">$</span>black <span class="sc">==</span> <span class="dv">1</span>])</span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>mean_pred_white <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>predicted[test<span class="sc">$</span>white <span class="sc">==</span> <span class="dv">1</span>])</span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a>actual_rate_black <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>recidivism[test<span class="sc">$</span>black <span class="sc">==</span> <span class="dv">1</span>])</span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a>actual_rate_white <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>recidivism[test<span class="sc">$</span>white <span class="sc">==</span> <span class="dv">1</span>])</span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a>num_black</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 729</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>num_white</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 495</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>mean_pred_black</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.511985</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>mean_pred_white</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3789606</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>actual_rate_black</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.521262</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>actual_rate_white</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4020202</code></pre>
</div>
</div>
<p>#Q6.5 yes there is a difference between the mean predicted recidivism rate of black defendents 0.512 and the mean predicted recidivism rate of white defendents 0.379. The actual recidivsm rate of black defenedents is higher than their predicted at 0.521, and the actual recidivism rate of white defendents is higher than their predicted at 0.402. The tradeoff of using prediction in criminal justice is that there are many omitted variables so we don’t know that something is causal. For instance, i implemented an instrumental variable on this dataset for judge toughness in another class. There is also a tradeoff on available information. Here there are just way more black individuals 729 than white 495, so we have more data to go off for them that is probably more accurate.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>